In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_Olympic_Medalists = pd.read_csv('Olympic_Medalists/all_olympic_medalists_with_continent_clean.csv')
df_Olympic_Medalists.head()

,season,year,medal,country_code,country,athletes,games,sport,event_gender,event_name,continent
0,Summer,1896,Gold,USA,United States,Thomas BURKE,1896 Athens,Athletics,Men's,100m,North America
1,Summer,1896,Silver,GER,Germany,Fritz HOFMANN,1896 Athens,Athletics,Men's,100m,Europe
2,Summer,1896,Bronze,HUN,Hungary,Alajos SZOKOLYI,1896 Athens,Athletics,Men's,100m,Europe
3,Summer,1896,Bronze,USA,United States,Francis LANE,1896 Athens,Athletics,Men's,100m,North America
4,Summer,1896,Gold,USA,United States,Thomas BURKE,1896 Athens,Athletics,Men's,400m,North America

In [24]:
#Earliest period in the dataset

df_Olympic_Medalists['year'].min()

1896

In [25]:
#latest period in the dataset

df_Olympic_Medalists['year'].max()

2024

In [5]:
# Getting information on the data types of each field
df_Olympic_Medalists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20247 entries, 0 to 20246
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   season        20247 non-null  object
 1   year          20247 non-null  int64
 2   medal         20243 non-null  object
 3   country_code  20243 non-null  object
 4   country       20243 non-null  object
 5   athletes      19820 non-null  object
 6   games         20247 non-null  object
 7   sport         20247 non-null  object
 8   event_gender  20247 non-null  object
 9   event_name    20247 non-null  object
 10  continent     20247 non-null  object
dtypes: int64(1), object(10)
memory usage: 1.7+ MB

In [6]:
# From the above with a total count of 20247 games but with 20243 medals we could tell that there were games that had no medals issues.
# First is to find out the full details of those games.
# Then we go ahead to drop them from the list

Events_No_Medals = df_Olympic_Medalists[df_Olympic_Medalists['medal'].isna()]

In [7]:
df_Olympic_Medalists[df_Olympic_Medalists['medal'].isna()]

,season,year,medal,country_code,country,athletes,games,sport,event_gender,event_name,continent
807,Summer,1908,NaN,NaN,NaN,NaN,1908 London,Cycling Track,Men's,sprint individual,Other
1559,Summer,1920,NaN,NaN,NaN,NaN,1920 Antwerp,Sailing,Mixed,18 foot dinghy,Other
2621,Summer,1932,NaN,NaN,NaN,NaN,1932 Los Angeles,Equestrian Jumping,Mixed,team,Other
16837,Winter,1928,NaN,NaN,NaN,NaN,1928 St. Moritz,Speed skating,Men's,10000m,Other

In [8]:
# Now drop events (rows) with no medals 

df_Olympic_Medalists_Clean = df_Olympic_Medalists.dropna(subset=['medal'])

In [10]:
# Now check if the 'clean' contains any events with no medals

df_Olympic_Medalists_Clean[df_Olympic_Medalists_Clean['medal'].isna()]

Empty DataFrame
Columns: [season, year, medal, country_code, country, athletes, games, sport, event_gender, event_name, continent]
Index: []

In [11]:
# So with the olympics they use to allowed 'mixed' team where athlete from different countries can compete against each other
# I will therefore filter out the mixed team into a separte data frame incase we need that for separate analysis

df_Olympic_Medalists_Mixed = df_Olympic_Medalists_Clean[df_Olympic_Medalists_Clean['country'] == 'Mixed Team']
df_Olympic_Medalists_Mixed

,season,year,medal,country_code,country,athletes,games,sport,event_gender,event_name,continent
110,Summer,1896,Gold,XXB,Mixed Team,"Friedrich TRAUN (GER), John BOLAND (GBR)",1896 Athens,Tennis,Men's,doubles,Other
112,Summer,1896,Bronze,XXB,Mixed Team,"George Stuart ROBERTSON (GBR), Edwin FLACK (AUS)",1896 Athens,Tennis,Men's,doubles,Other
379,Summer,1900,Silver,XXB,Mixed Team,"Basil Spalding DE GARMENDIA (USA), Max DECUGIS...",1900 Paris,Tennis,Men's,doubles,Other
383,Summer,1900,Silver,XXB,Mixed Team,"Harold Sergerson MAHONY (GBR), Hélène PREVOST ...",1900 Paris,Tennis,Mixed,mixed doubles,Other
384,Summer,1900,Bronze,XXB,Mixed Team,"Archibald A. WARDEN (GBR), Hedwig ROSENBAUM (BOH)",1900 Paris,Tennis,Mixed,mixed doubles,Other
385,Summer,1900,Bronze,XXB,Mixed Team,"Marion JONES Farquhar (USA), Hugh Lawrence DOH...",1900 Paris,Tennis,Mixed,mixed doubles,Other
403,Summer,1900,Bronze,XXB,Mixed Team,"Manuel de Escandón (MEX), Guillermo Hayden Wri...",1900 Paris,Polo,Men's,polo,Other
404,Summer,1900,Gold,XXB,Mixed Team,"Edgar AABYE (DEN), Gustaf SÖDERSTRÖM (SWE), Ka...",1900 Paris,Tug of War,Men's,tug of war,Other
547,Summer,1904,Gold,XXB,Mixed Team,"Ramon FONST (CUB), Albertson VAN ZO POST (USA)...",1904 St Louis,Fencing,Men's,foil team,Other

In [23]:
# Countries and number of medals per medal class, use the below code to find top 10 and bottom 10

Country_Medal_Count = df_Olympic_Medalists_Clean.groupby(['country', 'medal']).size().reset_index(name='no of medals').sort_values(by='no of medals', ascending=False)
pd.set_option('display.max_rows', None)
print(Country_Medal_Count)

                                      country   medal  no of medals
382                             United States    Gold          1177
383                             United States  Silver           955
381                             United States  Bronze           843
363                                      USSR    Gold           473
364                                      USSR  Silver           376
362                                      USSR  Bronze           355
120                                    France  Bronze           345
135                             Great Britain  Bronze           338
137                             Great Britain  Silver           325
122                                    France  Silver           310
131                                   Germany    Gold           307
132                                   Germany  Silver           307
130                                   Germany  Bronze           304
136                             Great Britain    Gold           291
65                                      China    Gold           287
121                                    France    Gold           273
179                                     Italy  Bronze           264
180                                     Italy    Gold           261
333                                    Sweden  Bronze           242
181                                     Italy  Silver           234
66                                      China  Silver           226
335                                    Sweden  Silver           226
56                                     Canada  Bronze           222
334                                    Sweden    Gold           213
17                                  Australia  Bronze           210
259                                    Norway    Gold           209
188                                     Japan  Bronze           204
64                                      China  Bronze           202
301                        Russian Federation    Gold           193
128                German Democratic Republic    Gold           192
19                                  Australia  Silver           192
300                        Russian Federation  Bronze           185
260                                    Norway  Silver           185
155                                   Hungary    Gold           183
58                                     Canada  Silver           182
117                                   Finland  Bronze           182
154                                   Hungary  Bronze           181
189                                     Japan    Gold           179
190                                     Japan  Silver           177
258                                    Norway  Bronze           174
18                                  Australia    Gold           171
129                German Democratic Republic  Silver           165
246                               Netherlands  Bronze           165
302                        Russian Federation  Silver           164
127                German Democratic Republic  Bronze           162
156                                   Hungary  Silver           156
247                               Netherlands    Gold           154
119                                   Finland  Silver           150
57                                     Canada    Gold           150
248                               Netherlands  Silver           149
118                                   Finland    Gold           146
277                                    Poland  Bronze           146
203                            Korea Republic    Gold           136
336                               Switzerland  Bronze           131
20                                    Austria  Bronze           130
204                            Korea Republic  Silver           126
338                               Switzerland  Silver           124
294                                   Romania  Bronze           124
22                                    Austria  Silver           122
202                            Korea Republic  Bronze           117
337                               Switzerland    Gold           114
296                                   Romania  Silver            98
279                                    Poland  Silver            95
112               Federal Republic of Germany  Bronze            94
295                                   Romania    Gold            92
21                                    Austria    Gold            92
50                                   Bulgaria  Silver            90
48                                   Bulgaria  Bronze            86
81                                       Cuba  Bronze            83
114               Federal Republic of Germany  Silver            82
91                                    Denmark  Bronze            80
82                                       Cuba    Gold            79
93                                    Denmark  Silver            77
278                                    Poland    Gold            76
44                                     Brazil  Bronze            73
328                                     Spain  Silver            69
113               Federal Republic of Germany    Gold            67
83                                       Cuba  Silver            67
36                                    Belgium  Bronze            65
368                                   Ukraine  Bronze            64
88                             Czechoslovakia  Bronze            60
376                   Unified Team of Germany  Silver            60
38                                    Belgium  Silver            58
251                               New Zealand    Gold            58
90                             Czechoslovakia  Silver            57
49                                   Bulgaria    Gold            55
326                                     Spain  Bronze            55
372                    Unified Team (ex USSR)    Gold            54
89                             Czechoslovakia    Gold            51
327                                     Spain    Gold            51
250                               New Zealand  Bronze            49
92                                    Denmark    Gold            47
138                                    Greece  Bronze            46
37                                    Belgium    Gold            46
140                                    Greece  Silver            45
33                                    Belarus  Bronze            44
373                    Unified Team (ex USSR)  Silver            44
46                                     Brazil  Silver            43
374                   Unified Team of Germany  Bronze            41
198                                     Kenya  Silver            40
369                                   Ukraine    Gold            40
196                                     Kenya  Bronze            39
360                                    Turkey    Gold            39
85                             Czech Republic  Bronze            38
371                    Unified Team (ex USSR)  Bronze            37
370                                   Ukraine  Silver            37
375                   Unified Team of Germany    Gold            36
252                               New Zealand  Silver            36
197                                     Kenya    Gold            35
193                                Kazakhstan  Bronze            34
325                              South Africa  Silver            34
35                                    Belarus  Silver            34
139                                    Greece    Gold            34
228                                    Mexico  Bronze            33
185                                   Jamaica  Silver            33
45                                     Brazil    Gold            33
399                                Yugoslavia  Silver            32
359                                    Turkey  Bronze            32
323                              South Africa  Bronze            31
169                                      Iran  Bronze            30
87                             Czech Republic  Silver            29
8                                   Argentina  Bronze            29
397                                Yugoslavia  Bronze            29
199                                 Korea DPR  Bronze            28
195                                Kazakhstan  Silver            28
86                             Czech Republic    Gold            28
324                              South Africa    Gold            27
230                                    Mexico  Silver            27
361                                    Turkey  Silver            27
171                                      Iran  Silver            27
23                                 Azerbaijan  Bronze            27
398                                Yugoslavia    Gold            26
10                                  Argentina  Silver            26
183                                   Jamaica  Bronze            24
170                                      Iran    Gold            24
110                                  Ethiopia    Gold            23
9                                   Argentina    Gold            22
320                                  Slovenia  Bronze            22
387                                Uzbekistan  Bronze            21
109                                  Ethiopia  Bronze            21
34                                    Belarus    Gold            20
184                                   Jamaica    Gold            20
201                                 Korea DPR  Silver            19
124                                   Georgia  Bronze            18
80                                    Croatia  Silver            18
346                                  Thailand  Bronze            18
106                                   Estonia  Bronze            18
79                                    Croatia    Gold            17
322                                  Slovenia  Silver            17
163                                     India  Bronze            17
319                                  Slovakia  Silver            16
70                                   Colombia  Bronze            16
388                                Uzbekistan    Gold            16
200                                 Korea DPR    Gold            16
67                             Chinese Taipei  Bronze            16
78                                    Croatia  Bronze            16
194                                Kazakhstan    Gold            16
219                                 Lithuania  Bronze            15
173                                   Ireland  Bronze            15
102                                     Egypt  Bronze            15
288                                       ROC  Bronze            15
111                                  Ethiopia  Silver            14
213                                    Latvia  Silver            14
236                                  Mongolia  Bronze            14
174                                   Ireland    Gold            13
280                                  Portugal  Bronze            13
168                                 Indonesia  Silver            13
240                                   Morocco  Bronze            13
229                                    Mexico    Gold            13
25                                 Azerbaijan  Silver            13
166                                 Indonesia  Bronze            13
318                                  Slovakia    Gold            13
107                                   Estonia    Gold            13
290                                       ROC  Silver            12
72                                   Colombia  Silver            12
255                                   Nigeria  Bronze            12
211                                    Latvia  Bronze            11
238                                  Mongolia  Silver            11
321                                  Slovenia    Gold            11
348                                  Thailand  Silver            11
125                                   Georgia    Gold            11
108                                   Estonia  Silver            11
126                                   Georgia  Silver            10
282                                  Portugal  Silver            10
347                                  Thailand    Gold            10
104                                     Egypt  Silver            10
175                                   Ireland  Silver            10
257                                   Nigeria  Silver            10
317                                  Slovakia  Bronze            10
351                       Trinidad and Tobago  Bronze             9
274                               Philippines  Bronze             9
167                                 Indonesia    Gold             9
390                                 Venezuela  Bronze             9
24                                 Azerbaijan    Gold             9
164                                     India    Gold             9
13                                    Armenia  Silver             9
5                                     Algeria  Bronze             9
261              Olympic Athletes from Russia  Bronze             9
283                               Puerto Rico  Bronze             8
103                                     Egypt    Gold             8
389                                Uzbekistan  Silver             8
221                                 Lithuania  Silver             8
356                                   Tunisia  Bronze             8
176                                    Israel  Bronze             8
63                                      Chile  Silver             8
165                                     India  Silver             8
226                                  Malaysia  Silver             7
209                                Kyrgyzstan  Bronze             7
6                                     Algeria    Gold             7
311                                    Serbia  Silver             7
309                                    Serbia  Bronze             7
11                                    Armenia  Bronze             7
241                                   Morocco    Gold             7
68                             Chinese Taipei    Gold             7
225                                  Malaysia  Bronze             6
220                                 Lithuania    Gold             6
69                             Chinese Taipei  Silver             6
27                                    Bahamas    Gold             6
234                                   Moldova  Bronze             6
384                                   Uruguay  Bronze             6
178                                    Israel  Silver             6
26                                    Bahamas  Bronze             6
216                             Liechtenstein  Bronze             6
263              Olympic Athletes from Russia  Silver             6
310                                    Serbia    Gold             6
342                                Tajikistan  Bronze             5
71                                   Colombia    Gold             5
289                                       ROC    Gold             5
14                                Australasia  Bronze             5
187                          Jamaica, British  Silver             5
242                                   Morocco  Silver             5
281                                  Portugal    Gold             5
357                                   Tunisia    Gold             5
245                                   Namibia  Silver             4
264                                  Pakistan  Bronze             4
353                       Trinidad and Tobago  Silver             4
265                                  Pakistan    Gold             4
299                            Russian Empire  Silver             4
286                                     Qatar  Bronze             4
392                                 Venezuela  Silver             4
367                                    Uganda  Silver             4
407                                  Zimbabwe  Silver             4
16                                Australasia  Silver             4
97                         Dominican Republic    Gold             4
30                                    Bahrain    Gold             4
61                                      Chile  Bronze             4
212                                    Latvia    Gold             4
231                                Mixed Team  Bronze             4
7                                     Algeria  Silver             4
96                         Dominican Republic  Bronze             4
232                                Mixed Team    Gold             3
313                                 Singapore  Bronze             3
276                               Philippines  Silver             3
186                          Jamaica, British    Gold             3
395                                   Vietnam  Silver             3
273                                      Peru  Silver             3
54                                   Cameroon    Gold             3
366                                    Uganda    Gold             3
15                                Australasia    Gold             3
2                                         AIN  Silver             3
400               Yugoslavia Federal Republic  Bronze             3
406                                  Zimbabwe    Gold             3
266                                  Pakistan  Silver             3
297                            Russian Empire  Bronze             3
210                                Kyrgyzstan  Silver             3
235                                   Moldova  Silver             3
62                                      Chile    Gold             3
358                                   Tunisia  Silver             3
40                                    Bohemia  Bronze             3
352                       Trinidad and Tobago    Gold             3
256                                   Nigeria    Gold             3
223                                Luxembourg  Silver             3
101                                   Ecuador  Silver             3
151                          Hong Kong, China  Bronze             3
133                                     Ghana  Bronze             3
47                        British West Indies  Bronze             2
306                              Saudi Arabia  Bronze             2
152                          Hong Kong, China    Gold             2
157                                   Iceland  Bronze             2
43                                   Botswana  Silver             2
141                                   Grenada  Bronze             2
312                     Serbia and Montenegro  Silver             2
53                                   Cameroon  Bronze             2
365                                    Uganda  Bronze             2
73                                 Costa Rica  Bronze             2
354              Trinidad and Tobago, British  Bronze             2
76                              Cote d'Ivoire  Bronze             2
100                                   Ecuador    Gold             2
99                                    Ecuador  Bronze             2
98                         Dominican Republic  Silver             2
84                                     Cyprus  Silver             2
158                                   Iceland  Silver             2
31                                    Bahrain  Silver             2

In [13]:
# Countries and number of olympic events they have participated in

Country_N0s_Events = df_Olympic_Medalists_Clean.groupby('country')['event_name'].size().reset_index(name='no of events').sort_values(by='no of events', ascending=False)
Country_N0s_Events

                  country  no of events
158         United States          2975
151                  USSR          1204
55          Great Britain           954
49                 France           928
53                Germany           918
..                    ...           ...
131    Singapore, British             1
61     Hong Kong, British             1
137                 Sudan             1
103  Netherlands Antilles             1
136             Sri Lanka             1

[168 rows x 2 columns]

In [14]:
# Top 10 Countries based on the number of events they have participated in 

Top10_Country_N0s_Events = df_Olympic_Medalists_Clean.groupby('country')['event_name'].size().nlargest(10).reset_index(name='no of events').sort_values(by='no of events', ascending=False)
Top10_Country_N0s_Events

         country  no of events
0  United States          2975
1           USSR          1204
2  Great Britain           954
3         France           928
4        Germany           918
5          Italy           759
6          China           715
7         Sweden           681
8      Australia           573
9         Norway           568

In [22]:
# Country and the number of olympic games participated in

Country_N0s_Participation = df_Olympic_Medalists_Clean.groupby('country')['games'].nunique().reset_index(name='no of participation').sort_values(by='no of participation', ascending=False)
pd.set_option('display.max_rows', None)
print(Country_N0s_Participation)

                                      country  no of participation
49                                     France                   52
158                             United States                   52
139                                    Sweden                   51
23                                     Canada                   51
140                               Switzerland                   50
8                                     Austria                   50
48                                    Finland                   49
107                                    Norway                   49
73                                      Italy                   47
55                              Great Britain                   46
102                               Netherlands                   43
77                                      Japan                   36
7                                   Australia                   35
63                                    Hungary                   35
14                                    Belgium                   32
114                                    Poland                   31
53                                    Germany                   30
37                                    Denmark                   29
36                             Czechoslovakia                   27
82                             Korea Republic                   26
104                               New Zealand                   25
135                                     Spain                   24
20                                   Bulgaria                   21
121                                   Romania                   21
94                                     Mexico                   21
4                                   Argentina                   20
56                                     Greece                   20
18                                     Brazil                   20
134                              South Africa                   19
27                                      China                   19
67                                      India                   19
151                                      USSR                   18
150                                    Turkey                   18
69                                       Iran                   17
164                                Yugoslavia                   16
115                                  Portugal                   16
33                                       Cuba                   16
71                                    Ireland                   14
133                                  Slovenia                   14
44                                    Estonia                   14
75                                    Jamaica                   14
13                                    Belarus                   14
35                             Czech Republic                   14
81                                  Korea DPR                   13
80                                      Kenya                   13
45                                   Ethiopia                   13
153                                   Ukraine                   13
86                                     Latvia                   13
79                                 Kazakhstan                   12
97                                   Mongolia                   12
123                        Russian Federation                   12
132                                  Slovakia                   12
32                                    Croatia                   12
52                 German Democratic Republic                   11
99                                    Morocco                   11
46                Federal Republic of Germany                   11
144                                  Thailand                   11
161                                 Venezuela                   10
29                                   Colombia                   10
42                                      Egypt                   10
109                                  Pakistan                   10
68                                  Indonesia                    9
113                               Philippines                    9
10                                    Bahamas                    9
106                                   Nigeria                    9
28                             Chinese Taipei                    9
159                                   Uruguay                    8
116                               Puerto Rico                    8
89                                  Lithuania                    8
3                                     Algeria                    8
160                                Uzbekistan                    8
26                                      Chile                    8
149                                   Tunisia                    8
147                       Trinidad and Tobago                    8
51                                    Georgia                    7
72                                     Israel                    7
9                                  Azerbaijan                    7
152                                    Uganda                    6
40                         Dominican Republic                    6
155                   Unified Team of Germany                    6
22                                   Cameroon                    6
92                                   Malaysia                    6
5                                     Armenia                    6
88                              Liechtenstein                    5
112                                      Peru                    5
117                                     Qatar                    5
128                                    Serbia                    4
90                                 Luxembourg                    4
130                                 Singapore                    4
54                                      Ghana                    4
162                                   Vietnam                    4
64                                    Iceland                    4
96                                    Moldova                    4
142                                Tajikistan                    4
110                                    Panama                    3
167                                  Zimbabwe                    3
95                                 Mixed Team                    3
141                                     Syria                    3
166                                    Zambia                    3
11                                    Bahrain                    3
30                                 Costa Rica                    3
41                                    Ecuador                    3
57                                    Grenada                    3
62                           Hong Kong, China                    3
85                                 Kyrgyzstan                    3
87                                    Lebanon                    3
120                Republic of China (Taiwan)                    2
126                              Saudi Arabia                    2
138                                  Suriname                    2
154                    Unified Team (ex USSR)                    2
122                            Russian Empire                    2
156                      United Arab Emirates                    2
165               Yugoslavia Federal Republic                    2
148              Trinidad and Tobago, British                    2
84                                     Kuwait                    2
1                                 Afghanistan                    2
17                                   Botswana                    2
60                                      Haiti                    2
47                                       Fiji                    2
34                                     Cyprus                    2
31                              Cote d'Ivoire                    2
76                           Jamaica, British                    2
78                                     Jordan                    2
83                                     Kosovo                    2
21                                    Burundi                    2
58                                  Guatemala                    2
16                                    Bohemia                    2
6                                 Australasia                    2
105                                     Niger                    2
100                                Mozambique                    2
101                                   Namibia                    2
50                                      Gabon                    1
2                                     Albania                    1
43                                    Eritrea                    1
39                                   Dominica                    1
38                                   Djibouti                    1
25                                     Ceylon                    1
12                                   Barbados                    1
19                        British West Indies                    1
163                        Virgin Islands, US                    1
24                                 Cape Verde                    1
146                                     Tonga                    1
157       United Arab Republic (Egypt, Syria)                    1
15                                    Bermuda                    1
111                                  Paraguay                    1
61                         Hong Kong, British                    1
145                                      Togo                    1
59                                     Guyana                    1
118                                       ROC                    1
119                      Refugee Olympic Team                    1
103                      Netherlands Antilles                    1
98                                 Montenegro                    1
124                               Saint Lucia                    1
125                                     Samoa                    1
93                                  Mauritius                    1
127                                   Senegal                    1
91                                  Macedonia                    1
129                     Serbia and Montenegro                    1
131                        Singapore, British                    1
74                                Ivory Coast                    1
136                                 Sri Lanka                    1
137                                     Sudan                    1
70                                       Iraq                    1
66   Independent Participants (ex Yugoslavia)                    1
65               Independent Olympic Athletes                    1
108              Olympic Athletes from Russia                    1
143                                  Tanzania                    1
0                                         AIN                    1

In [16]:
# Medals count by continent

df_Olympic_Medalists_Clean.groupby('continent')['medal'].size().reset_index(name='no of medals').sort_values(by='no of medals', ascending=False)

       continent  no of medals
2         Europe         10399
3  North America          3962
1           Asia          2243
5          Other          2118
4        Oceania           732
0         Africa           440
6  South America           349

In [17]:
# Top 10 in terms of number of olympic games participated in

Top10_Country_N0s_Participation = df_Olympic_Medalists_Clean.groupby('country')['games'].nunique().nlargest(10).reset_index(name='no of participation').sort_values(by='no of participation', ascending=False)
Top10_Country_N0s_Participation

         country  no of participation
0         France                   52
1  United States                   52
2         Canada                   51
3         Sweden                   51
4        Austria                   50
5    Switzerland                   50
6        Finland                   49
7         Norway                   49
8          Italy                   47
9  Great Britain                   46

In [19]:
# Top 10 count by medals

Top10_Country_N0s_Medals = df_Olympic_Medalists_Clean.groupby('country')['medal'].size().nlargest(10).reset_index(name='total medals').sort_values(by='total medals', ascending=False).head(10)
Top10_Country_N0s_Medals

         country  total medals
0  United States          2975
1           USSR          1204
2  Great Britain           954
3         France           928
4        Germany           918
5          Italy           759
6          China           715
7         Sweden           681
8      Australia           573
9         Norway           568

In [20]:
# Country, no of participation, events participated, medals count

df_mergeMedals_Participation =pd.merge(Top10_Country_N0s_Medals, Country_N0s_Participation, on='country', how='left')
Top10_df_Snapshot_CountryPerfm = pd.merge(df_mergeMedals_Participation, Country_N0s_Events, on='country', how='left')
Top10_df_Snapshot_CountryPerfm

         country  total medals  no of participation  no of events
0  United States          2975                   52          2975
1           USSR          1204                   18          1204
2  Great Britain           954                   46           954
3         France           928                   52           928
4        Germany           918                   30           918
5          Italy           759                   47           759
6          China           715                   19           715
7         Sweden           681                   51           681
8      Australia           573                   35           573
9         Norway           568                   49           568

In [21]:
# Bottom 10 in terms of number of olympic games participated in

df_Olympic_Medalists_Clean.groupby('country')['games'].nunique().nsmallest(10).reset_index(name='no of participation').sort_values(by='no of participation', ascending=False)

               country  no of participation
0                  AIN                    1
1              Albania                    1
2             Barbados                    1
3              Bermuda                    1
4  British West Indies                    1
5           Cape Verde                    1
6               Ceylon                    1
7             Djibouti                    1
8             Dominica                    1
9              Eritrea                    1

In [23]:
# Country Medals by distribution of event_gender

Medals_By_Gender = df_Olympic_Medalists_Clean.groupby(['country','event_gender']).size().reset_index(name='medals per gender')
Medals_By_Gender

                         country event_gender  medals per gender
0                            AIN        Men's                  3
1                            AIN      Women's                  2
2                    Afghanistan        Men's                  2
3                        Albania        Men's                  2
4                        Algeria        Men's                 15
..                           ...          ...                ...
330                   Yugoslavia      Women's                 10
331  Yugoslavia Federal Republic        Men's                  4
332  Yugoslavia Federal Republic      Women's                  3
333                       Zambia        Men's                  3
334                     Zimbabwe      Women's                  8

[335 rows x 3 columns]

In [24]:
# Top 10 country list

Top_10_countries_List = (df_Olympic_Medalists_Clean.groupby('country')['medal'].size().reset_index(name='total medals').sort_values(by='total medals', ascending=False).head(10))['country'].tolist()
Top_10_countries_List

['United States',
 'USSR',
 'Great Britain',
 'France',
 'Germany',
 'Italy',
 'China',
 'Sweden',
 'Australia',
 'Norway']

In [25]:
# Filter new data frame to include who countries in top 10

Filtered_Countries_Top10 = Medals_By_Gender[Medals_By_Gender['country'].isin(Top_10_countries_List)]
Filtered_Countries_Top10

           country event_gender  medals per gender
12       Australia        Men's                311
13       Australia        Mixed                 28
14       Australia      Women's                234
55           China        Men's                287
56           China        Mixed                 23
57           China      Women's                405
103         France        Men's                651
104         France        Mixed                101
105         France      Women's                176
112        Germany        Men's                511
113        Germany        Mixed                 93
114        Germany      Women's                314
116  Great Britain        Men's                637
117  Great Britain        Mixed                 94
118  Great Britain      Women's                223
152          Italy        Men's                548
153          Italy        Mixed                 55
154          Italy      Women's                156
216         Norway        Men's                427
217         Norway        Mixed                 38
218         Norway      Women's                103
280         Sweden        Men's                492
281         Sweden        Mixed                 79
282         Sweden      Women's                110
302           USSR        Men's                811
303           USSR        Mixed                 62
304           USSR      Women's                331
318  United States        Men's               1978
319  United States        Mixed                142
320  United States      Women's                855

In [27]:
df_Olympic_Medalists.nunique()

season              2
year               37
medal               3
country_code      158
country           168
athletes        16352
games              53
sport              77
event_gender        3
event_name        716
continent           7
dtype: int64

In [28]:
df_Olympic_Medalists.describe()

               year
count  20247.000000
mean    1979.503235
std       33.805505
min     1896.000000
25%     1960.000000
50%     1988.000000
75%     2008.000000
max     2024.000000

In [31]:
# Countries with atleast 1 gold

df_Countries_WithGold = df_Olympic_Medalists_Clean[df_Olympic_Medalists_Clean['medal'] == 'Gold']['country'].unique()
df_Countries_WithGold

array(['United States', 'Australia', 'Greece', 'France', 'Austria',
       'Germany', 'Switzerland', 'Hungary', 'Great Britain', 'Denmark',
       'Belgium', 'Luxembourg', 'Canada', 'Italy', 'Cuba', 'Netherlands',
       'Spain', 'Norway', 'South Africa', 'Sweden', 'Australasia',
       'Finland', 'Russian Empire', 'Brazil', 'Estonia', 'Uruguay',
       'Yugoslavia', 'Czechoslovakia', 'Argentina', 'Japan', 'Ireland',
       'Poland', 'New Zealand', 'India', 'Egypt', 'Turkey',
       'Jamaica, British', 'Mexico', 'Peru', 'USSR', 'Romania',
       'Unified Team of Germany', 'Iran', 'Bulgaria', 'Ethiopia',
       'Pakistan', 'Bahamas', 'Kenya', 'Tunisia',
       'German Democratic Republic', 'Federal Republic of Germany',
       'Venezuela', 'Uganda', 'Korea DPR', 'Trinidad and Tobago',
       'Jamaica', 'Korea Republic', 'Zimbabwe', 'Morocco', 'Portugal',
       'China', 'Suriname', 'Unified Team (ex USSR)', 'Lithuania',
       'Algeria', 'Indonesia', 'Burundi', 'Ecuador', 'Czech Republic',
       'Russian Federation', 'Nigeria', 'Ukraine', 'Syria', 'Thailand',
       'Kazakhstan', 'Slovakia', 'Croatia', 'Belarus',
       'Hong Kong, British', 'Yugoslavia Federal Republic', 'Costa Rica',
       'Armenia', 'Mozambique', 'Uzbekistan', 'Cameroon', 'Latvia',
       'Slovenia', 'Azerbaijan', 'Colombia', 'Dominican Republic',
       'Georgia', 'Israel', 'United Arab Emirates', 'Chinese Taipei',
       'Chile', 'Panama', 'Mongolia', 'Grenada', 'Bahrain', 'Serbia',
       'Tajikistan', 'Kosovo', 'Fiji', 'Vietnam',
       'Independent Olympic Athletes', 'Singapore', 'Jordan',
       "Cote d'Ivoire", 'Puerto Rico', 'Botswana', 'Saint Lucia',
       'Dominica', 'Hong Kong, China', 'Philippines', 'Guatemala', 'AIN',
       'Liechtenstein', 'Olympic Athletes from Russia', 'ROC'],
      dtype=object)

In [55]:
len(np.unique(df_Countries_WithGold))

119